up:
	@docker-compose up -d
	@echo Please access with a web browser: http://localhost:8000

down:
	@docker-compose down

exec-php:
	@docker-compose exec app bash

exec-nginx:
	@docker-compose exec web bash

exec-db:
	@docker-compose exec mysql mysql -u root -ppassword

